### PR TITLE
Update Release branch.

### PR DESCRIPTION
**Pull request by DeadLineSS13**
# About this PR
When we will update version, we need update this branch and compiling this branch only. Because develop branch only for developers with settings debug.
# Fixed issue:
#116

### CODE REVIEW

**Comment by RedlineTriad** [comment]
Why does this include 2 commits that aren't in develop?

**Comment by RedlineTriad** [comment]
Also, this doesn't fix the issue it says it fixes.

**Review by RedlineTriad — CHANGES_REQUESTED** [review]
Why does this include 2 commits that aren't in develop?
And the description says it fixes an issue that it doesn't actually fix.

**Comment by DeadLineSS13** [comment]
> Why does this include 2 commits that aren't in develop?
> And the description says it fixes an issue that it doesn't actually fix.
First commit it is updating branch release.
I forget update file with this fixe. One second.

**Comment by RedlineTriad** [comment]
The version bump from @corp-0 isn't included either.

**Comment by DeadLineSS13** [comment]
> The version bump from @corp-0 isn't included either.

Because this PR don't merged.

**Comment by RedlineTriad** [comment]
> > The version bump from @corp-0 isn't included either.
> 
> Because this PR don't merged.

I don't think merging this makes sense unless that is included.

**Comment by RedlineTriad** [comment]
Also, we shouldn't merge from your fork, we should merge from unitystation/develop into uniystation/release

**Comment by DeadLineSS13** [comment]
> Also, we shouldn't merge from your fork, we should merge from unitystation/develop into uniystation/release

Sounds smarter.

**Comment by DeadLineSS13** [comment]
Closed

**Pull request closed without merging**
