### PR TITLE
Refactors pinging into its own service and add unit tests for Servers Panel

### PR DESCRIPTION
**Pull request by CorruptComputer**
Most of the servers panel should be unit tested now. (minus downloading and launching the game)

### CODE REVIEW

**Comment by CorruptComputer** [comment]
The Codacy issue is a false positive, that parameter needs to be there to match the method signature expected by ReactiveUI. If it is removed it will fail to even compile.

**Comment by corp-0** [comment]
what are we using to mock? I read Moq was compromised.

Edit: the issue https://github.com/moq/moq/issues/1372

**Comment by CorruptComputer** [comment]
We are using Moq, but from what I can read there this was introduced in 4.20.0, and we are on 4.18.4 so we should be fine.

```
<PackageReference Include="Moq" Version="4.18.4" />
```

Edit: It also looks like this SponsorLink thing was removed in the latest version: https://github.com/moq/moq/releases/tag/v4.20.2

**Comment by corp-0** [comment]
> Edit: It also looks like this SponsorLink thing was removed in the latest version

Maybe, but trust is forever harmed

**Review by corp-0 — APPROVED** [review]

**Pull request merged**
