### PR TITLE
Upgrade Avalonia and other NuGet packages

### PR DESCRIPTION
**Pull request by CorruptComputer**
Should be ready now, also adds a pop-up window for when the code scan fails.

image

### CODE REVIEW

**Comment by corp-0** [comment]
Does this depend on the other PR updating dotnet?

**Comment by CorruptComputer** [comment]
No it doesn't, I kept it at 7.0 for these changes

**Comment by corp-0** [comment]
How is the new version of Avalonia related to upgrading dotnet then?

Do we really need to update Avalonia?

**Comment by CorruptComputer** [comment]
The warning here: https://github.com/unitystation/stationhub/actions/runs/7316971571/job/19932278559?pr=224#step:5:10

Warning: /usr/share/dotnet/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(284,5): warning NETSDK1206: Found version-specific or distribution-specific runtime identifier(s): win7-x64, win7-x86. Affected libraries: Avalonia.Angle.Windows.Natives. In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details. [/home/runner/work/stationhub/stationhub/UnitystationLauncher/UnitystationLauncher.csproj]

**Comment by corp-0** [comment]
it is not the prettiest popup ever, but it is serviceable. Thanks

**Pull request merged**
